dist: trusty


env:
  # Use test credentials for sequelize
  - NODE_ENV=dev

sudo: required
before_install:
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.5.1-1
addons:

language: node_js
node_js:
  - "9"

cache:
  yarn: true
  directories:
     - ./node_modules

install:
  - yarn install

notifications:
  email: false


deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"
    app: maexit-new
